import type React from "react"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import "./globals.css"
import MobileNavbar from "./_components/mobile-view/shared-ui/mobile-navbar"
import Footer from "./_components/mobile-view/shared-ui/footer"
import DesktopNav from "./_components/desktop-view/shared-ui/desktop-navbar"
import { Providers } from "./providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}  antialiased bg-[#ede4d2]`}>
        <Providers>
          {/* Desktop navigation: hidden on small screens, visible on md+ */}
          <nav className="hidden xl:block">
            <DesktopNav />
          </nav>
          {/* Mobile navigation: visible on small screens, hidden on md+ */}
          <nav className="block xl:hidden">
            <MobileNavbar />
          </nav>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}

export const metadata = {
      generator: 'v0.app'
    };
